import Navigation from '@/components/Navigation';
import Logo from '@/components/Logo';

export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
        </header>
        <Navigation />
        <main>{children}</main>
        <footer>
          <h3> Copyright by The Wild Oasis </h3>
        </footer>
      </body>
    </html>
  );
}
